// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseBadge: typeof import('./src/components/BaseBadge.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseIcon: typeof import('./src/components/BaseIcon.vue')['default']
    Ethereum: typeof import('./src/components/icons/Ethereum.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    Metamask: typeof import('./src/components/icons/Metamask.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    OpenSea: typeof import('./src/components/icons/OpenSea.vue')['default']
    Pathfinder: typeof import('./src/components/Pathfinder.vue')['default']
    Polygon: typeof import('./src/components/icons/Polygon.vue')['default']
    Star: typeof import('./src/components/icons/Star.vue')['default']
  }
}

export { }
